### ISSUE TITLE
Issue on page /06/relationaler_entwurf.html

### ISSUE THREAD

**Issue by Janmm14** [LUH-DBS/GDBS_Script#1]
Anzahl an Relationen (bei n Entitytypen)
□ Null-Stil: Nur eine Relation
□ ER-Stil: n Relationen
□ OO-Stil: O(2n-1) Relationen 

Falsch: bei OO-Stil müsste es 2^(n-1) sein, auf den Folien ist es korrekt.

**Comment by Ziawasch** [comment]
Korrigiert. Danke.
