### ISSUE TITLE
Issue on page /06/relationaler_entwurf.html

### ISSUE THREAD

**Issue by Letyri** [LUH-DBS/GDBS_Script#3]
Bei 6.2.5.2. Beispiel 2
<img width="620" alt="image" src="https://github.com/LUH-DBS/GDBS_Script/assets/66308890/0e82bb6e-89a5-4de0-a35a-6bdf105eaa2c">

Sollte es nicht ist_unter_Vertrag(Titel, Jahr, SchauspielerName, StudioName, Gehalt) sein?

**Comment by Ziawasch** [comment]
Wird korrigiert. Danke.
